// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package moetnmeoe.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class formatPhoneNumber extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __OrderObject;
	private moetnmeoe.proxies.Order OrderObject;

	public formatPhoneNumber(IContext context, IMendixObject OrderObject)
	{
		super(context);
		this.__OrderObject = OrderObject;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.OrderObject = __OrderObject == null ? null : moetnmeoe.proxies.Order.initialize(getContext(), __OrderObject);

		// BEGIN USER CODE
		String assetsAssetName = this.OrderObject.getContactPhone(this.getContext());
		assetsAssetName = assetsAssetName.replaceAll("[^0-9]", "");
		int lengthofString = assetsAssetName.length();
		if(lengthofString == 10) {
			assetsAssetName = assetsAssetName.replaceFirst("(\\d{3})(\\d{3})(\\d+)", "$1-$2-$3");
		} else {
			assetsAssetName = assetsAssetName.replaceFirst("(\\d{3})(\\d{3})(\\d{4})(\\d+)", "$1-$2-$3 $4");
		}

		return new StringBuilder(assetsAssetName).toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "formatPhoneNumber";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
