// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package moetnmeoe.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.net.URL;
import java.net.URLConnection;
import com.mendix.core.Core;
import java.io.InputStream;

public class retrievePDF extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __DocumentObj;
	private confirmation.proxies.PdfFiles DocumentObj;
	private java.lang.String AuthString;
	private java.lang.String Url;

	public retrievePDF(IContext context, IMendixObject DocumentObj, java.lang.String AuthString, java.lang.String Url)
	{
		super(context);
		this.__DocumentObj = DocumentObj;
		this.AuthString = AuthString;
		this.Url = Url;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.DocumentObj = __DocumentObj == null ? null : confirmation.proxies.PdfFiles.initialize(getContext(), __DocumentObj);

		// BEGIN USER CODE
		URLConnection conn = new URL(Url).openConnection();

		conn.setDoInput(true);
		conn.setDoOutput(true);
		conn.setRequestProperty("Content-Type", "application/pdf");
		conn.setRequestProperty("Authorization", AuthString);

		try (
			InputStream is = conn.getInputStream()
		) {
		// Get the response
			Core.storeFileDocumentContent(getContext(), __DocumentObj, is);
		}

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "retrievePDF";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
