// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public class Attribute
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject attributeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAML20.Attribute";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		NameFormat("NameFormat"),
		FriendlyName("FriendlyName"),
		isRequired("isRequired"),
		ManuallyCreated("ManuallyCreated"),
		Updated("Updated"),
		IsInCommonFederation("IsInCommonFederation"),
		Attribute_AttributeConsumingService("SAML20.Attribute_AttributeConsumingService"),
		Attribute_RoleDescriptor("SAML20.Attribute_RoleDescriptor"),
		Attribute_IdPMetadata("SAML20.Attribute_IdPMetadata");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Attribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAML20.Attribute"));
	}

	protected Attribute(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject attributeMendixObject)
	{
		if (attributeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SAML20.Attribute", attributeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAML20.Attribute");

		this.attributeMendixObject = attributeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Attribute.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static saml20.proxies.Attribute initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return saml20.proxies.Attribute.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static saml20.proxies.Attribute initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new saml20.proxies.Attribute(context, mendixObject);
	}

	public static saml20.proxies.Attribute load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return saml20.proxies.Attribute.initialize(context, mendixObject);
	}

	public static java.util.List<saml20.proxies.Attribute> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<saml20.proxies.Attribute> result = new java.util.ArrayList<saml20.proxies.Attribute>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SAML20.Attribute" + xpathConstraint))
			result.add(saml20.proxies.Attribute.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of NameFormat
	 */
	public final java.lang.String getNameFormat()
	{
		return getNameFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of NameFormat
	 */
	public final java.lang.String getNameFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NameFormat.toString());
	}

	/**
	 * Set value of NameFormat
	 * @param nameformat
	 */
	public final void setNameFormat(java.lang.String nameformat)
	{
		setNameFormat(getContext(), nameformat);
	}

	/**
	 * Set value of NameFormat
	 * @param context
	 * @param nameformat
	 */
	public final void setNameFormat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nameformat)
	{
		getMendixObject().setValue(context, MemberNames.NameFormat.toString(), nameformat);
	}

	/**
	 * @return value of FriendlyName
	 */
	public final java.lang.String getFriendlyName()
	{
		return getFriendlyName(getContext());
	}

	/**
	 * @param context
	 * @return value of FriendlyName
	 */
	public final java.lang.String getFriendlyName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FriendlyName.toString());
	}

	/**
	 * Set value of FriendlyName
	 * @param friendlyname
	 */
	public final void setFriendlyName(java.lang.String friendlyname)
	{
		setFriendlyName(getContext(), friendlyname);
	}

	/**
	 * Set value of FriendlyName
	 * @param context
	 * @param friendlyname
	 */
	public final void setFriendlyName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String friendlyname)
	{
		getMendixObject().setValue(context, MemberNames.FriendlyName.toString(), friendlyname);
	}

	/**
	 * @return value of isRequired
	 */
	public final java.lang.Boolean getisRequired()
	{
		return getisRequired(getContext());
	}

	/**
	 * @param context
	 * @return value of isRequired
	 */
	public final java.lang.Boolean getisRequired(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isRequired.toString());
	}

	/**
	 * Set value of isRequired
	 * @param isrequired
	 */
	public final void setisRequired(java.lang.Boolean isrequired)
	{
		setisRequired(getContext(), isrequired);
	}

	/**
	 * Set value of isRequired
	 * @param context
	 * @param isrequired
	 */
	public final void setisRequired(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isrequired)
	{
		getMendixObject().setValue(context, MemberNames.isRequired.toString(), isrequired);
	}

	/**
	 * @return value of ManuallyCreated
	 */
	public final java.lang.Boolean getManuallyCreated()
	{
		return getManuallyCreated(getContext());
	}

	/**
	 * @param context
	 * @return value of ManuallyCreated
	 */
	public final java.lang.Boolean getManuallyCreated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ManuallyCreated.toString());
	}

	/**
	 * Set value of ManuallyCreated
	 * @param manuallycreated
	 */
	public final void setManuallyCreated(java.lang.Boolean manuallycreated)
	{
		setManuallyCreated(getContext(), manuallycreated);
	}

	/**
	 * Set value of ManuallyCreated
	 * @param context
	 * @param manuallycreated
	 */
	public final void setManuallyCreated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean manuallycreated)
	{
		getMendixObject().setValue(context, MemberNames.ManuallyCreated.toString(), manuallycreated);
	}

	/**
	 * @return value of Updated
	 */
	public final java.lang.Boolean getUpdated()
	{
		return getUpdated(getContext());
	}

	/**
	 * @param context
	 * @return value of Updated
	 */
	public final java.lang.Boolean getUpdated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Updated.toString());
	}

	/**
	 * Set value of Updated
	 * @param updated
	 */
	public final void setUpdated(java.lang.Boolean updated)
	{
		setUpdated(getContext(), updated);
	}

	/**
	 * Set value of Updated
	 * @param context
	 * @param updated
	 */
	public final void setUpdated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean updated)
	{
		getMendixObject().setValue(context, MemberNames.Updated.toString(), updated);
	}

	/**
	 * @return value of IsInCommonFederation
	 */
	public final java.lang.Boolean getIsInCommonFederation()
	{
		return getIsInCommonFederation(getContext());
	}

	/**
	 * @param context
	 * @return value of IsInCommonFederation
	 */
	public final java.lang.Boolean getIsInCommonFederation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsInCommonFederation.toString());
	}

	/**
	 * Set value of IsInCommonFederation
	 * @param isincommonfederation
	 */
	public final void setIsInCommonFederation(java.lang.Boolean isincommonfederation)
	{
		setIsInCommonFederation(getContext(), isincommonfederation);
	}

	/**
	 * Set value of IsInCommonFederation
	 * @param context
	 * @param isincommonfederation
	 */
	public final void setIsInCommonFederation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isincommonfederation)
	{
		getMendixObject().setValue(context, MemberNames.IsInCommonFederation.toString(), isincommonfederation);
	}

	/**
	 * @return value of Attribute_AttributeConsumingService
	 */
	public final saml20.proxies.AttributeConsumingService getAttribute_AttributeConsumingService() throws com.mendix.core.CoreException
	{
		return getAttribute_AttributeConsumingService(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute_AttributeConsumingService
	 */
	public final saml20.proxies.AttributeConsumingService getAttribute_AttributeConsumingService(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.AttributeConsumingService result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attribute_AttributeConsumingService.toString());
		if (identifier != null)
			result = saml20.proxies.AttributeConsumingService.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Attribute_AttributeConsumingService
	 * @param attribute_attributeconsumingservice
	 */
	public final void setAttribute_AttributeConsumingService(saml20.proxies.AttributeConsumingService attribute_attributeconsumingservice)
	{
		setAttribute_AttributeConsumingService(getContext(), attribute_attributeconsumingservice);
	}

	/**
	 * Set value of Attribute_AttributeConsumingService
	 * @param context
	 * @param attribute_attributeconsumingservice
	 */
	public final void setAttribute_AttributeConsumingService(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.AttributeConsumingService attribute_attributeconsumingservice)
	{
		if (attribute_attributeconsumingservice == null)
			getMendixObject().setValue(context, MemberNames.Attribute_AttributeConsumingService.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Attribute_AttributeConsumingService.toString(), attribute_attributeconsumingservice.getMendixObject().getId());
	}

	/**
	 * @return value of Attribute_RoleDescriptor
	 */
	public final saml20.proxies.RoleDescriptor getAttribute_RoleDescriptor() throws com.mendix.core.CoreException
	{
		return getAttribute_RoleDescriptor(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute_RoleDescriptor
	 */
	public final saml20.proxies.RoleDescriptor getAttribute_RoleDescriptor(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.RoleDescriptor result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attribute_RoleDescriptor.toString());
		if (identifier != null)
			result = saml20.proxies.RoleDescriptor.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Attribute_RoleDescriptor
	 * @param attribute_roledescriptor
	 */
	public final void setAttribute_RoleDescriptor(saml20.proxies.RoleDescriptor attribute_roledescriptor)
	{
		setAttribute_RoleDescriptor(getContext(), attribute_roledescriptor);
	}

	/**
	 * Set value of Attribute_RoleDescriptor
	 * @param context
	 * @param attribute_roledescriptor
	 */
	public final void setAttribute_RoleDescriptor(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.RoleDescriptor attribute_roledescriptor)
	{
		if (attribute_roledescriptor == null)
			getMendixObject().setValue(context, MemberNames.Attribute_RoleDescriptor.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Attribute_RoleDescriptor.toString(), attribute_roledescriptor.getMendixObject().getId());
	}

	/**
	 * @return value of Attribute_IdPMetadata
	 */
	public final saml20.proxies.IdPMetadata getAttribute_IdPMetadata() throws com.mendix.core.CoreException
	{
		return getAttribute_IdPMetadata(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute_IdPMetadata
	 */
	public final saml20.proxies.IdPMetadata getAttribute_IdPMetadata(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.IdPMetadata result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attribute_IdPMetadata.toString());
		if (identifier != null)
			result = saml20.proxies.IdPMetadata.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Attribute_IdPMetadata
	 * @param attribute_idpmetadata
	 */
	public final void setAttribute_IdPMetadata(saml20.proxies.IdPMetadata attribute_idpmetadata)
	{
		setAttribute_IdPMetadata(getContext(), attribute_idpmetadata);
	}

	/**
	 * Set value of Attribute_IdPMetadata
	 * @param context
	 * @param attribute_idpmetadata
	 */
	public final void setAttribute_IdPMetadata(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.IdPMetadata attribute_idpmetadata)
	{
		if (attribute_idpmetadata == null)
			getMendixObject().setValue(context, MemberNames.Attribute_IdPMetadata.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Attribute_IdPMetadata.toString(), attribute_idpmetadata.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return attributeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final saml20.proxies.Attribute that = (saml20.proxies.Attribute) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAML20.Attribute";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
