// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public enum BindingType
{
	SAML_2_0_HTTP_POST(new java.lang.String[][] { new java.lang.String[] { "en_US", "SAML:2.0 HTTP-POST" }, new java.lang.String[] { "nl_NL", "SAML:2.0 HTTP-Artifact" }, new java.lang.String[] { "en_GB", "SAML:2.0 HTTP-POST" }, new java.lang.String[] { "en_ZA", "SAML:2.0 HTTP-POST" }, new java.lang.String[] { "ja_JP", "SAML:2.0 HTTP-POST" } }),
	SAML_2_0_HTTP_POST_SimpleSign(new java.lang.String[][] { new java.lang.String[] { "en_US", "SAML:2.0 HTTP-POST-SimpleSign" }, new java.lang.String[] { "nl_NL", "SAML:2.0 HTTP-POST-SimpleSign" }, new java.lang.String[] { "en_GB", "SAML:2.0 HTTP-POST-SimpleSign" }, new java.lang.String[] { "en_ZA", "SAML:2.0 HTTP-POST-SimpleSign" }, new java.lang.String[] { "ja_JP", "SAML:2.0 HTTP-POST-SimpleSign" } }),
	SAML_2_0_HTTP_Redirect(new java.lang.String[][] { new java.lang.String[] { "en_US", "SAML:2.0 HTTP-Redirect" }, new java.lang.String[] { "nl_NL", "SAML:2.0 HTTP-Redirect" }, new java.lang.String[] { "en_GB", "SAML:2.0 HTTP-Redirect" }, new java.lang.String[] { "en_ZA", "SAML:2.0 HTTP-Redirect" }, new java.lang.String[] { "ja_JP", "SAML:2.0 HTTP-Redirect" } }),
	SAML_2_0_SOAP(new java.lang.String[][] { new java.lang.String[] { "en_US", "SAML:2.0 SOAP" }, new java.lang.String[] { "nl_NL", "SAML:2.0 SOAP" }, new java.lang.String[] { "en_GB", "SAML:2.0 SOAP" }, new java.lang.String[] { "en_ZA", "SAML:2.0 SOAP" }, new java.lang.String[] { "ja_JP", "SAML:2.0 SOAP" } }),
	SAML_2_0_HTTP_Artifact(new java.lang.String[][] { new java.lang.String[] { "en_US", "SAML:2.0 HTTP-Artifact" }, new java.lang.String[] { "nl_NL", "SAML:2.0 HTTP-Artifact" }, new java.lang.String[] { "en_GB", "SAML:2.0 HTTP-Artifact" }, new java.lang.String[] { "en_ZA", "SAML:2.0 HTTP-Artifact" }, new java.lang.String[] { "ja_JP", "SAML:2.0 HTTP-Artifact" } }),
	SAML_2_0_PAOS(new java.lang.String[][] { new java.lang.String[] { "en_US", "SAML:2.0 PAOS" }, new java.lang.String[] { "nl_NL", "SAML:2.0 PAOS" }, new java.lang.String[] { "en_GB", "SAML:2.0 PAOS" }, new java.lang.String[] { "en_ZA", "SAML:2.0 PAOS" }, new java.lang.String[] { "ja_JP", "SAML:2.0 PAOS" } }),
	SAML_2_0_SSO_browser(new java.lang.String[][] { new java.lang.String[] { "en_US", "SAML:2.0 SSO:browser" }, new java.lang.String[] { "nl_NL", "SAML:2.0 SSO:browser" }, new java.lang.String[] { "en_GB", "SAML:2.0 SSO:browser" }, new java.lang.String[] { "en_ZA", "SAML:2.0 SSO:browser" }, new java.lang.String[] { "ja_JP", "SAML:2.0 SSO:browser" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private BindingType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
