// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public enum EncryptionMethod
{
	SHA1withRSA(new java.lang.String[][] { new java.lang.String[] { "en_US", "SHA1 - RSA" }, new java.lang.String[] { "nl_NL", "SHA1 - RSA" }, new java.lang.String[] { "en_GB", "SHA1 - RSA" }, new java.lang.String[] { "en_ZA", "SHA1 - RSA" }, new java.lang.String[] { "ja_JP", "SHA1 - RSA" } }),
	SHA256WithRSA(new java.lang.String[][] { new java.lang.String[] { "en_US", "SHA256 - RSA" }, new java.lang.String[] { "nl_NL", "SHA256 - RSA" }, new java.lang.String[] { "en_GB", "SHA256 - RSA" }, new java.lang.String[] { "en_ZA", "SHA256 - RSA" }, new java.lang.String[] { "ja_JP", "SHA256 - RSA" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private EncryptionMethod(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
