// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public enum EncryptionKeyLength
{
	_1024bit_Encryption(new java.lang.String[][] { new java.lang.String[] { "en_US", "1024 bits" }, new java.lang.String[] { "nl_NL", "1024 bits" }, new java.lang.String[] { "en_GB", "1024 bits" }, new java.lang.String[] { "en_ZA", "1024 bits" }, new java.lang.String[] { "ja_JP", "1024 bits" } }),
	_2048bit_Encryption(new java.lang.String[][] { new java.lang.String[] { "en_US", "2048 bits" }, new java.lang.String[] { "nl_NL", "2048 bits" }, new java.lang.String[] { "en_GB", "2048 bits" }, new java.lang.String[] { "en_ZA", "2048 bits" }, new java.lang.String[] { "ja_JP", "2048 bits" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private EncryptionKeyLength(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
