// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public class EntitiesDescriptor
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject entitiesDescriptorMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAML20.EntitiesDescriptor";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		validUntil("validUntil"),
		cacheDuration("cacheDuration"),
		_ID("_ID"),
		Name("Name"),
		Updated("Updated"),
		EntitiesDescriptor_IdPMetadata("SAML20.EntitiesDescriptor_IdPMetadata"),
		EntitiesDescriptor_KeyInfo("SAML20.EntitiesDescriptor_KeyInfo");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EntitiesDescriptor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAML20.EntitiesDescriptor"));
	}

	protected EntitiesDescriptor(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject entitiesDescriptorMendixObject)
	{
		if (entitiesDescriptorMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SAML20.EntitiesDescriptor", entitiesDescriptorMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAML20.EntitiesDescriptor");

		this.entitiesDescriptorMendixObject = entitiesDescriptorMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EntitiesDescriptor.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static saml20.proxies.EntitiesDescriptor initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return saml20.proxies.EntitiesDescriptor.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static saml20.proxies.EntitiesDescriptor initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new saml20.proxies.EntitiesDescriptor(context, mendixObject);
	}

	public static saml20.proxies.EntitiesDescriptor load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return saml20.proxies.EntitiesDescriptor.initialize(context, mendixObject);
	}

	public static java.util.List<saml20.proxies.EntitiesDescriptor> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<saml20.proxies.EntitiesDescriptor> result = new java.util.ArrayList<saml20.proxies.EntitiesDescriptor>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SAML20.EntitiesDescriptor" + xpathConstraint))
			result.add(saml20.proxies.EntitiesDescriptor.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of validUntil
	 */
	public final java.util.Date getvalidUntil()
	{
		return getvalidUntil(getContext());
	}

	/**
	 * @param context
	 * @return value of validUntil
	 */
	public final java.util.Date getvalidUntil(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.validUntil.toString());
	}

	/**
	 * Set value of validUntil
	 * @param validuntil
	 */
	public final void setvalidUntil(java.util.Date validuntil)
	{
		setvalidUntil(getContext(), validuntil);
	}

	/**
	 * Set value of validUntil
	 * @param context
	 * @param validuntil
	 */
	public final void setvalidUntil(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date validuntil)
	{
		getMendixObject().setValue(context, MemberNames.validUntil.toString(), validuntil);
	}

	/**
	 * @return value of cacheDuration
	 */
	public final java.lang.String getcacheDuration()
	{
		return getcacheDuration(getContext());
	}

	/**
	 * @param context
	 * @return value of cacheDuration
	 */
	public final java.lang.String getcacheDuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.cacheDuration.toString());
	}

	/**
	 * Set value of cacheDuration
	 * @param cacheduration
	 */
	public final void setcacheDuration(java.lang.String cacheduration)
	{
		setcacheDuration(getContext(), cacheduration);
	}

	/**
	 * Set value of cacheDuration
	 * @param context
	 * @param cacheduration
	 */
	public final void setcacheDuration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cacheduration)
	{
		getMendixObject().setValue(context, MemberNames.cacheDuration.toString(), cacheduration);
	}

	/**
	 * @return value of _ID
	 */
	public final java.lang.String get_ID()
	{
		return get_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of _ID
	 */
	public final java.lang.String get_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._ID.toString());
	}

	/**
	 * Set value of _ID
	 * @param _id
	 */
	public final void set_ID(java.lang.String _id)
	{
		set_ID(getContext(), _id);
	}

	/**
	 * Set value of _ID
	 * @param context
	 * @param _id
	 */
	public final void set_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._ID.toString(), _id);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Updated
	 */
	public final java.lang.Boolean getUpdated()
	{
		return getUpdated(getContext());
	}

	/**
	 * @param context
	 * @return value of Updated
	 */
	public final java.lang.Boolean getUpdated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Updated.toString());
	}

	/**
	 * Set value of Updated
	 * @param updated
	 */
	public final void setUpdated(java.lang.Boolean updated)
	{
		setUpdated(getContext(), updated);
	}

	/**
	 * Set value of Updated
	 * @param context
	 * @param updated
	 */
	public final void setUpdated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean updated)
	{
		getMendixObject().setValue(context, MemberNames.Updated.toString(), updated);
	}

	/**
	 * @return value of EntitiesDescriptor_IdPMetadata
	 */
	public final saml20.proxies.IdPMetadata getEntitiesDescriptor_IdPMetadata() throws com.mendix.core.CoreException
	{
		return getEntitiesDescriptor_IdPMetadata(getContext());
	}

	/**
	 * @param context
	 * @return value of EntitiesDescriptor_IdPMetadata
	 */
	public final saml20.proxies.IdPMetadata getEntitiesDescriptor_IdPMetadata(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.IdPMetadata result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EntitiesDescriptor_IdPMetadata.toString());
		if (identifier != null)
			result = saml20.proxies.IdPMetadata.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EntitiesDescriptor_IdPMetadata
	 * @param entitiesdescriptor_idpmetadata
	 */
	public final void setEntitiesDescriptor_IdPMetadata(saml20.proxies.IdPMetadata entitiesdescriptor_idpmetadata)
	{
		setEntitiesDescriptor_IdPMetadata(getContext(), entitiesdescriptor_idpmetadata);
	}

	/**
	 * Set value of EntitiesDescriptor_IdPMetadata
	 * @param context
	 * @param entitiesdescriptor_idpmetadata
	 */
	public final void setEntitiesDescriptor_IdPMetadata(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.IdPMetadata entitiesdescriptor_idpmetadata)
	{
		if (entitiesdescriptor_idpmetadata == null)
			getMendixObject().setValue(context, MemberNames.EntitiesDescriptor_IdPMetadata.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EntitiesDescriptor_IdPMetadata.toString(), entitiesdescriptor_idpmetadata.getMendixObject().getId());
	}

	/**
	 * @return value of EntitiesDescriptor_KeyInfo
	 */
	public final saml20.proxies.KeyInfo getEntitiesDescriptor_KeyInfo() throws com.mendix.core.CoreException
	{
		return getEntitiesDescriptor_KeyInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of EntitiesDescriptor_KeyInfo
	 */
	public final saml20.proxies.KeyInfo getEntitiesDescriptor_KeyInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.KeyInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EntitiesDescriptor_KeyInfo.toString());
		if (identifier != null)
			result = saml20.proxies.KeyInfo.load(context, identifier);
		return result;
	}

	/**
	 * Set value of EntitiesDescriptor_KeyInfo
	 * @param entitiesdescriptor_keyinfo
	 */
	public final void setEntitiesDescriptor_KeyInfo(saml20.proxies.KeyInfo entitiesdescriptor_keyinfo)
	{
		setEntitiesDescriptor_KeyInfo(getContext(), entitiesdescriptor_keyinfo);
	}

	/**
	 * Set value of EntitiesDescriptor_KeyInfo
	 * @param context
	 * @param entitiesdescriptor_keyinfo
	 */
	public final void setEntitiesDescriptor_KeyInfo(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.KeyInfo entitiesdescriptor_keyinfo)
	{
		if (entitiesdescriptor_keyinfo == null)
			getMendixObject().setValue(context, MemberNames.EntitiesDescriptor_KeyInfo.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.EntitiesDescriptor_KeyInfo.toString(), entitiesdescriptor_keyinfo.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return entitiesDescriptorMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final saml20.proxies.EntitiesDescriptor that = (saml20.proxies.EntitiesDescriptor) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAML20.EntitiesDescriptor";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
