// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public enum IdentifyingAssertionType
{
	IdP_Provided(new java.lang.String[][] { new java.lang.String[] { "en_US", "IdP Provided" }, new java.lang.String[] { "nl_NL", "Door IdP Opgegeven" }, new java.lang.String[] { "en_GB", "IdP Provided" }, new java.lang.String[] { "en_ZA", "IdP Provided" }, new java.lang.String[] { "ja_JP", "IdP Provided" } }),
	InCommon_Federation(new java.lang.String[][] { new java.lang.String[] { "en_US", "InCommon Federation" }, new java.lang.String[] { "nl_NL", "InCommon Federation" }, new java.lang.String[] { "en_GB", "InCommon Federation" }, new java.lang.String[] { "en_ZA", "InCommon Federation" }, new java.lang.String[] { "ja_JP", "InCommon Federation" } }),
	Use_Name_ID(new java.lang.String[][] { new java.lang.String[] { "en_US", "Use Name ID" }, new java.lang.String[] { "en_ZA", "Use Name ID" }, new java.lang.String[] { "en_GB", "Use Name ID" }, new java.lang.String[] { "nl_NL", "Gebruik Name ID" }, new java.lang.String[] { "ja_JP", "Use Name ID" } }),
	Custom(new java.lang.String[][] { new java.lang.String[] { "en_US", "Custom" }, new java.lang.String[] { "nl_NL", "Custom" }, new java.lang.String[] { "en_GB", "Custom" }, new java.lang.String[] { "en_ZA", "Custom" }, new java.lang.String[] { "ja_JP", "Custom" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private IdentifyingAssertionType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
