// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public class KeyDescriptor
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject keyDescriptorMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAML20.KeyDescriptor";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		use("use"),
		KeyDescriptor_RoleDescriptor("SAML20.KeyDescriptor_RoleDescriptor"),
		KeyDescriptor_KeyInfo("SAML20.KeyDescriptor_KeyInfo");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public KeyDescriptor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAML20.KeyDescriptor"));
	}

	protected KeyDescriptor(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject keyDescriptorMendixObject)
	{
		if (keyDescriptorMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SAML20.KeyDescriptor", keyDescriptorMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAML20.KeyDescriptor");

		this.keyDescriptorMendixObject = keyDescriptorMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'KeyDescriptor.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static saml20.proxies.KeyDescriptor initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return saml20.proxies.KeyDescriptor.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static saml20.proxies.KeyDescriptor initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new saml20.proxies.KeyDescriptor(context, mendixObject);
	}

	public static saml20.proxies.KeyDescriptor load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return saml20.proxies.KeyDescriptor.initialize(context, mendixObject);
	}

	public static java.util.List<saml20.proxies.KeyDescriptor> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<saml20.proxies.KeyDescriptor> result = new java.util.ArrayList<saml20.proxies.KeyDescriptor>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SAML20.KeyDescriptor" + xpathConstraint))
			result.add(saml20.proxies.KeyDescriptor.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of use
	 */
	public final java.lang.String getuse()
	{
		return getuse(getContext());
	}

	/**
	 * @param context
	 * @return value of use
	 */
	public final java.lang.String getuse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.use.toString());
	}

	/**
	 * Set value of use
	 * @param use
	 */
	public final void setuse(java.lang.String use)
	{
		setuse(getContext(), use);
	}

	/**
	 * Set value of use
	 * @param context
	 * @param use
	 */
	public final void setuse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String use)
	{
		getMendixObject().setValue(context, MemberNames.use.toString(), use);
	}

	/**
	 * @return value of KeyDescriptor_RoleDescriptor
	 */
	public final saml20.proxies.RoleDescriptor getKeyDescriptor_RoleDescriptor() throws com.mendix.core.CoreException
	{
		return getKeyDescriptor_RoleDescriptor(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyDescriptor_RoleDescriptor
	 */
	public final saml20.proxies.RoleDescriptor getKeyDescriptor_RoleDescriptor(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.RoleDescriptor result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KeyDescriptor_RoleDescriptor.toString());
		if (identifier != null)
			result = saml20.proxies.RoleDescriptor.load(context, identifier);
		return result;
	}

	/**
	 * Set value of KeyDescriptor_RoleDescriptor
	 * @param keydescriptor_roledescriptor
	 */
	public final void setKeyDescriptor_RoleDescriptor(saml20.proxies.RoleDescriptor keydescriptor_roledescriptor)
	{
		setKeyDescriptor_RoleDescriptor(getContext(), keydescriptor_roledescriptor);
	}

	/**
	 * Set value of KeyDescriptor_RoleDescriptor
	 * @param context
	 * @param keydescriptor_roledescriptor
	 */
	public final void setKeyDescriptor_RoleDescriptor(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.RoleDescriptor keydescriptor_roledescriptor)
	{
		if (keydescriptor_roledescriptor == null)
			getMendixObject().setValue(context, MemberNames.KeyDescriptor_RoleDescriptor.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.KeyDescriptor_RoleDescriptor.toString(), keydescriptor_roledescriptor.getMendixObject().getId());
	}

	/**
	 * @return value of KeyDescriptor_KeyInfo
	 */
	public final saml20.proxies.KeyInfo getKeyDescriptor_KeyInfo() throws com.mendix.core.CoreException
	{
		return getKeyDescriptor_KeyInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyDescriptor_KeyInfo
	 */
	public final saml20.proxies.KeyInfo getKeyDescriptor_KeyInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.KeyInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KeyDescriptor_KeyInfo.toString());
		if (identifier != null)
			result = saml20.proxies.KeyInfo.load(context, identifier);
		return result;
	}

	/**
	 * Set value of KeyDescriptor_KeyInfo
	 * @param keydescriptor_keyinfo
	 */
	public final void setKeyDescriptor_KeyInfo(saml20.proxies.KeyInfo keydescriptor_keyinfo)
	{
		setKeyDescriptor_KeyInfo(getContext(), keydescriptor_keyinfo);
	}

	/**
	 * Set value of KeyDescriptor_KeyInfo
	 * @param context
	 * @param keydescriptor_keyinfo
	 */
	public final void setKeyDescriptor_KeyInfo(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.KeyInfo keydescriptor_keyinfo)
	{
		if (keydescriptor_keyinfo == null)
			getMendixObject().setValue(context, MemberNames.KeyDescriptor_KeyInfo.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.KeyDescriptor_KeyInfo.toString(), keydescriptor_keyinfo.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return keyDescriptorMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final saml20.proxies.KeyDescriptor that = (saml20.proxies.KeyDescriptor) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAML20.KeyDescriptor";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
