// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public class LoginFeedback
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject loginFeedbackMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAML20.LoginFeedback";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LoginAllowed("LoginAllowed"),
		FeedbackMessageHTML("FeedbackMessageHTML");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LoginFeedback(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAML20.LoginFeedback"));
	}

	protected LoginFeedback(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject loginFeedbackMendixObject)
	{
		if (loginFeedbackMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SAML20.LoginFeedback", loginFeedbackMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAML20.LoginFeedback");

		this.loginFeedbackMendixObject = loginFeedbackMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'LoginFeedback.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static saml20.proxies.LoginFeedback initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return saml20.proxies.LoginFeedback.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static saml20.proxies.LoginFeedback initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new saml20.proxies.LoginFeedback(context, mendixObject);
	}

	public static saml20.proxies.LoginFeedback load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return saml20.proxies.LoginFeedback.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of LoginAllowed
	 */
	public final java.lang.Boolean getLoginAllowed()
	{
		return getLoginAllowed(getContext());
	}

	/**
	 * @param context
	 * @return value of LoginAllowed
	 */
	public final java.lang.Boolean getLoginAllowed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.LoginAllowed.toString());
	}

	/**
	 * Set value of LoginAllowed
	 * @param loginallowed
	 */
	public final void setLoginAllowed(java.lang.Boolean loginallowed)
	{
		setLoginAllowed(getContext(), loginallowed);
	}

	/**
	 * Set value of LoginAllowed
	 * @param context
	 * @param loginallowed
	 */
	public final void setLoginAllowed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean loginallowed)
	{
		getMendixObject().setValue(context, MemberNames.LoginAllowed.toString(), loginallowed);
	}

	/**
	 * @return value of FeedbackMessageHTML
	 */
	public final java.lang.String getFeedbackMessageHTML()
	{
		return getFeedbackMessageHTML(getContext());
	}

	/**
	 * @param context
	 * @return value of FeedbackMessageHTML
	 */
	public final java.lang.String getFeedbackMessageHTML(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FeedbackMessageHTML.toString());
	}

	/**
	 * Set value of FeedbackMessageHTML
	 * @param feedbackmessagehtml
	 */
	public final void setFeedbackMessageHTML(java.lang.String feedbackmessagehtml)
	{
		setFeedbackMessageHTML(getContext(), feedbackmessagehtml);
	}

	/**
	 * Set value of FeedbackMessageHTML
	 * @param context
	 * @param feedbackmessagehtml
	 */
	public final void setFeedbackMessageHTML(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String feedbackmessagehtml)
	{
		getMendixObject().setValue(context, MemberNames.FeedbackMessageHTML.toString(), feedbackmessagehtml);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return loginFeedbackMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final saml20.proxies.LoginFeedback that = (saml20.proxies.LoginFeedback) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAML20.LoginFeedback";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
