// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public class RoleDescriptor
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject roleDescriptorMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAML20.RoleDescriptor";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_ID("_ID"),
		validUntil("validUntil"),
		cacheDuration("cacheDuration"),
		protocolSupportEnumeration("protocolSupportEnumeration"),
		errorURL("errorURL"),
		AuthnRequestsSigned("AuthnRequestsSigned"),
		WantAuthnRequestsSigned("WantAuthnRequestsSigned"),
		WantAssertionsSigned("WantAssertionsSigned"),
		RoleDescriptorType("RoleDescriptorType"),
		RoleDescriptor_Organization("SAML20.RoleDescriptor_Organization"),
		RoleDescriptor_EntityDescriptor("SAML20.RoleDescriptor_EntityDescriptor");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RoleDescriptor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAML20.RoleDescriptor"));
	}

	protected RoleDescriptor(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject roleDescriptorMendixObject)
	{
		if (roleDescriptorMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SAML20.RoleDescriptor", roleDescriptorMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAML20.RoleDescriptor");

		this.roleDescriptorMendixObject = roleDescriptorMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RoleDescriptor.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static saml20.proxies.RoleDescriptor initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return saml20.proxies.RoleDescriptor.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static saml20.proxies.RoleDescriptor initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new saml20.proxies.RoleDescriptor(context, mendixObject);
	}

	public static saml20.proxies.RoleDescriptor load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return saml20.proxies.RoleDescriptor.initialize(context, mendixObject);
	}

	public static java.util.List<saml20.proxies.RoleDescriptor> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<saml20.proxies.RoleDescriptor> result = new java.util.ArrayList<saml20.proxies.RoleDescriptor>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SAML20.RoleDescriptor" + xpathConstraint))
			result.add(saml20.proxies.RoleDescriptor.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _ID
	 */
	public final java.lang.String get_ID()
	{
		return get_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of _ID
	 */
	public final java.lang.String get_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._ID.toString());
	}

	/**
	 * Set value of _ID
	 * @param _id
	 */
	public final void set_ID(java.lang.String _id)
	{
		set_ID(getContext(), _id);
	}

	/**
	 * Set value of _ID
	 * @param context
	 * @param _id
	 */
	public final void set_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._ID.toString(), _id);
	}

	/**
	 * @return value of validUntil
	 */
	public final java.util.Date getvalidUntil()
	{
		return getvalidUntil(getContext());
	}

	/**
	 * @param context
	 * @return value of validUntil
	 */
	public final java.util.Date getvalidUntil(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.validUntil.toString());
	}

	/**
	 * Set value of validUntil
	 * @param validuntil
	 */
	public final void setvalidUntil(java.util.Date validuntil)
	{
		setvalidUntil(getContext(), validuntil);
	}

	/**
	 * Set value of validUntil
	 * @param context
	 * @param validuntil
	 */
	public final void setvalidUntil(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date validuntil)
	{
		getMendixObject().setValue(context, MemberNames.validUntil.toString(), validuntil);
	}

	/**
	 * @return value of cacheDuration
	 */
	public final java.lang.String getcacheDuration()
	{
		return getcacheDuration(getContext());
	}

	/**
	 * @param context
	 * @return value of cacheDuration
	 */
	public final java.lang.String getcacheDuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.cacheDuration.toString());
	}

	/**
	 * Set value of cacheDuration
	 * @param cacheduration
	 */
	public final void setcacheDuration(java.lang.String cacheduration)
	{
		setcacheDuration(getContext(), cacheduration);
	}

	/**
	 * Set value of cacheDuration
	 * @param context
	 * @param cacheduration
	 */
	public final void setcacheDuration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cacheduration)
	{
		getMendixObject().setValue(context, MemberNames.cacheDuration.toString(), cacheduration);
	}

	/**
	 * @return value of protocolSupportEnumeration
	 */
	public final java.lang.String getprotocolSupportEnumeration()
	{
		return getprotocolSupportEnumeration(getContext());
	}

	/**
	 * @param context
	 * @return value of protocolSupportEnumeration
	 */
	public final java.lang.String getprotocolSupportEnumeration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.protocolSupportEnumeration.toString());
	}

	/**
	 * Set value of protocolSupportEnumeration
	 * @param protocolsupportenumeration
	 */
	public final void setprotocolSupportEnumeration(java.lang.String protocolsupportenumeration)
	{
		setprotocolSupportEnumeration(getContext(), protocolsupportenumeration);
	}

	/**
	 * Set value of protocolSupportEnumeration
	 * @param context
	 * @param protocolsupportenumeration
	 */
	public final void setprotocolSupportEnumeration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String protocolsupportenumeration)
	{
		getMendixObject().setValue(context, MemberNames.protocolSupportEnumeration.toString(), protocolsupportenumeration);
	}

	/**
	 * @return value of errorURL
	 */
	public final java.lang.String geterrorURL()
	{
		return geterrorURL(getContext());
	}

	/**
	 * @param context
	 * @return value of errorURL
	 */
	public final java.lang.String geterrorURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.errorURL.toString());
	}

	/**
	 * Set value of errorURL
	 * @param errorurl
	 */
	public final void seterrorURL(java.lang.String errorurl)
	{
		seterrorURL(getContext(), errorurl);
	}

	/**
	 * Set value of errorURL
	 * @param context
	 * @param errorurl
	 */
	public final void seterrorURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String errorurl)
	{
		getMendixObject().setValue(context, MemberNames.errorURL.toString(), errorurl);
	}

	/**
	 * @return value of AuthnRequestsSigned
	 */
	public final java.lang.Boolean getAuthnRequestsSigned()
	{
		return getAuthnRequestsSigned(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthnRequestsSigned
	 */
	public final java.lang.Boolean getAuthnRequestsSigned(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AuthnRequestsSigned.toString());
	}

	/**
	 * Set value of AuthnRequestsSigned
	 * @param authnrequestssigned
	 */
	public final void setAuthnRequestsSigned(java.lang.Boolean authnrequestssigned)
	{
		setAuthnRequestsSigned(getContext(), authnrequestssigned);
	}

	/**
	 * Set value of AuthnRequestsSigned
	 * @param context
	 * @param authnrequestssigned
	 */
	public final void setAuthnRequestsSigned(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean authnrequestssigned)
	{
		getMendixObject().setValue(context, MemberNames.AuthnRequestsSigned.toString(), authnrequestssigned);
	}

	/**
	 * @return value of WantAuthnRequestsSigned
	 */
	public final java.lang.Boolean getWantAuthnRequestsSigned()
	{
		return getWantAuthnRequestsSigned(getContext());
	}

	/**
	 * @param context
	 * @return value of WantAuthnRequestsSigned
	 */
	public final java.lang.Boolean getWantAuthnRequestsSigned(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WantAuthnRequestsSigned.toString());
	}

	/**
	 * Set value of WantAuthnRequestsSigned
	 * @param wantauthnrequestssigned
	 */
	public final void setWantAuthnRequestsSigned(java.lang.Boolean wantauthnrequestssigned)
	{
		setWantAuthnRequestsSigned(getContext(), wantauthnrequestssigned);
	}

	/**
	 * Set value of WantAuthnRequestsSigned
	 * @param context
	 * @param wantauthnrequestssigned
	 */
	public final void setWantAuthnRequestsSigned(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean wantauthnrequestssigned)
	{
		getMendixObject().setValue(context, MemberNames.WantAuthnRequestsSigned.toString(), wantauthnrequestssigned);
	}

	/**
	 * @return value of WantAssertionsSigned
	 */
	public final java.lang.Boolean getWantAssertionsSigned()
	{
		return getWantAssertionsSigned(getContext());
	}

	/**
	 * @param context
	 * @return value of WantAssertionsSigned
	 */
	public final java.lang.Boolean getWantAssertionsSigned(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WantAssertionsSigned.toString());
	}

	/**
	 * Set value of WantAssertionsSigned
	 * @param wantassertionssigned
	 */
	public final void setWantAssertionsSigned(java.lang.Boolean wantassertionssigned)
	{
		setWantAssertionsSigned(getContext(), wantassertionssigned);
	}

	/**
	 * Set value of WantAssertionsSigned
	 * @param context
	 * @param wantassertionssigned
	 */
	public final void setWantAssertionsSigned(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean wantassertionssigned)
	{
		getMendixObject().setValue(context, MemberNames.WantAssertionsSigned.toString(), wantassertionssigned);
	}

	/**
	 * Set value of RoleDescriptorType
	 * @param roledescriptortype
	 */
	public final saml20.proxies.RoleDescriptorType getRoleDescriptorType()
	{
		return getRoleDescriptorType(getContext());
	}

	/**
	 * @param context
	 * @return value of RoleDescriptorType
	 */
	public final saml20.proxies.RoleDescriptorType getRoleDescriptorType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RoleDescriptorType.toString());
		if (obj == null)
			return null;

		return saml20.proxies.RoleDescriptorType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RoleDescriptorType
	 * @param roledescriptortype
	 */
	public final void setRoleDescriptorType(saml20.proxies.RoleDescriptorType roledescriptortype)
	{
		setRoleDescriptorType(getContext(), roledescriptortype);
	}

	/**
	 * Set value of RoleDescriptorType
	 * @param context
	 * @param roledescriptortype
	 */
	public final void setRoleDescriptorType(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.RoleDescriptorType roledescriptortype)
	{
		if (roledescriptortype != null)
			getMendixObject().setValue(context, MemberNames.RoleDescriptorType.toString(), roledescriptortype.toString());
		else
			getMendixObject().setValue(context, MemberNames.RoleDescriptorType.toString(), null);
	}

	/**
	 * @return value of RoleDescriptor_Organization
	 */
	public final saml20.proxies.Organization getRoleDescriptor_Organization() throws com.mendix.core.CoreException
	{
		return getRoleDescriptor_Organization(getContext());
	}

	/**
	 * @param context
	 * @return value of RoleDescriptor_Organization
	 */
	public final saml20.proxies.Organization getRoleDescriptor_Organization(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.Organization result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RoleDescriptor_Organization.toString());
		if (identifier != null)
			result = saml20.proxies.Organization.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RoleDescriptor_Organization
	 * @param roledescriptor_organization
	 */
	public final void setRoleDescriptor_Organization(saml20.proxies.Organization roledescriptor_organization)
	{
		setRoleDescriptor_Organization(getContext(), roledescriptor_organization);
	}

	/**
	 * Set value of RoleDescriptor_Organization
	 * @param context
	 * @param roledescriptor_organization
	 */
	public final void setRoleDescriptor_Organization(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.Organization roledescriptor_organization)
	{
		if (roledescriptor_organization == null)
			getMendixObject().setValue(context, MemberNames.RoleDescriptor_Organization.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RoleDescriptor_Organization.toString(), roledescriptor_organization.getMendixObject().getId());
	}

	/**
	 * @return value of RoleDescriptor_EntityDescriptor
	 */
	public final saml20.proxies.EntityDescriptor getRoleDescriptor_EntityDescriptor() throws com.mendix.core.CoreException
	{
		return getRoleDescriptor_EntityDescriptor(getContext());
	}

	/**
	 * @param context
	 * @return value of RoleDescriptor_EntityDescriptor
	 */
	public final saml20.proxies.EntityDescriptor getRoleDescriptor_EntityDescriptor(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.EntityDescriptor result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RoleDescriptor_EntityDescriptor.toString());
		if (identifier != null)
			result = saml20.proxies.EntityDescriptor.load(context, identifier);
		return result;
	}

	/**
	 * Set value of RoleDescriptor_EntityDescriptor
	 * @param roledescriptor_entitydescriptor
	 */
	public final void setRoleDescriptor_EntityDescriptor(saml20.proxies.EntityDescriptor roledescriptor_entitydescriptor)
	{
		setRoleDescriptor_EntityDescriptor(getContext(), roledescriptor_entitydescriptor);
	}

	/**
	 * Set value of RoleDescriptor_EntityDescriptor
	 * @param context
	 * @param roledescriptor_entitydescriptor
	 */
	public final void setRoleDescriptor_EntityDescriptor(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.EntityDescriptor roledescriptor_entitydescriptor)
	{
		if (roledescriptor_entitydescriptor == null)
			getMendixObject().setValue(context, MemberNames.RoleDescriptor_EntityDescriptor.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.RoleDescriptor_EntityDescriptor.toString(), roledescriptor_entitydescriptor.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return roleDescriptorMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final saml20.proxies.RoleDescriptor that = (saml20.proxies.RoleDescriptor) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAML20.RoleDescriptor";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
