// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public class SAMLRequest extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAML20.SAMLRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RequestID("RequestID"),
		hasRequest("hasRequest"),
		hasResponse("hasResponse"),
		ReturnedPrincipal("ReturnedPrincipal"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		SAMLRequest_SAMLResponse("SAML20.SAMLRequest_SAMLResponse"),
		SAMLRequest_SSOConfiguration("SAML20.SAMLRequest_SSOConfiguration"),
		SAMLRequest_Endpoint("SAML20.SAMLRequest_Endpoint");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SAMLRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAML20.SAMLRequest"));
	}

	protected SAMLRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sAMLRequestMendixObject)
	{
		super(context, sAMLRequestMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("SAML20.SAMLRequest", sAMLRequestMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAML20.SAMLRequest");
	}

	/**
	 * @deprecated Use 'SAMLRequest.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static saml20.proxies.SAMLRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return saml20.proxies.SAMLRequest.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static saml20.proxies.SAMLRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new saml20.proxies.SAMLRequest(context, mendixObject);
	}

	public static saml20.proxies.SAMLRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return saml20.proxies.SAMLRequest.initialize(context, mendixObject);
	}

	public static java.util.List<saml20.proxies.SAMLRequest> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<saml20.proxies.SAMLRequest> result = new java.util.ArrayList<saml20.proxies.SAMLRequest>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SAML20.SAMLRequest" + xpathConstraint))
			result.add(saml20.proxies.SAMLRequest.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of RequestID
	 */
	public final java.lang.String getRequestID()
	{
		return getRequestID(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestID
	 */
	public final java.lang.String getRequestID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RequestID.toString());
	}

	/**
	 * Set value of RequestID
	 * @param requestid
	 */
	public final void setRequestID(java.lang.String requestid)
	{
		setRequestID(getContext(), requestid);
	}

	/**
	 * Set value of RequestID
	 * @param context
	 * @param requestid
	 */
	public final void setRequestID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String requestid)
	{
		getMendixObject().setValue(context, MemberNames.RequestID.toString(), requestid);
	}

	/**
	 * Set value of hasRequest
	 * @param hasrequest
	 */
	public final saml20.proxies.YesNo gethasRequest()
	{
		return gethasRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of hasRequest
	 */
	public final saml20.proxies.YesNo gethasRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.hasRequest.toString());
		if (obj == null)
			return null;

		return saml20.proxies.YesNo.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of hasRequest
	 * @param hasrequest
	 */
	public final void sethasRequest(saml20.proxies.YesNo hasrequest)
	{
		sethasRequest(getContext(), hasrequest);
	}

	/**
	 * Set value of hasRequest
	 * @param context
	 * @param hasrequest
	 */
	public final void sethasRequest(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.YesNo hasrequest)
	{
		if (hasrequest != null)
			getMendixObject().setValue(context, MemberNames.hasRequest.toString(), hasrequest.toString());
		else
			getMendixObject().setValue(context, MemberNames.hasRequest.toString(), null);
	}

	/**
	 * Set value of hasResponse
	 * @param hasresponse
	 */
	public final saml20.proxies.YesNo gethasResponse()
	{
		return gethasResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of hasResponse
	 */
	public final saml20.proxies.YesNo gethasResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.hasResponse.toString());
		if (obj == null)
			return null;

		return saml20.proxies.YesNo.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of hasResponse
	 * @param hasresponse
	 */
	public final void sethasResponse(saml20.proxies.YesNo hasresponse)
	{
		sethasResponse(getContext(), hasresponse);
	}

	/**
	 * Set value of hasResponse
	 * @param context
	 * @param hasresponse
	 */
	public final void sethasResponse(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.YesNo hasresponse)
	{
		if (hasresponse != null)
			getMendixObject().setValue(context, MemberNames.hasResponse.toString(), hasresponse.toString());
		else
			getMendixObject().setValue(context, MemberNames.hasResponse.toString(), null);
	}

	/**
	 * @return value of ReturnedPrincipal
	 */
	public final java.lang.String getReturnedPrincipal()
	{
		return getReturnedPrincipal(getContext());
	}

	/**
	 * @param context
	 * @return value of ReturnedPrincipal
	 */
	public final java.lang.String getReturnedPrincipal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReturnedPrincipal.toString());
	}

	/**
	 * Set value of ReturnedPrincipal
	 * @param returnedprincipal
	 */
	public final void setReturnedPrincipal(java.lang.String returnedprincipal)
	{
		setReturnedPrincipal(getContext(), returnedprincipal);
	}

	/**
	 * Set value of ReturnedPrincipal
	 * @param context
	 * @param returnedprincipal
	 */
	public final void setReturnedPrincipal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String returnedprincipal)
	{
		getMendixObject().setValue(context, MemberNames.ReturnedPrincipal.toString(), returnedprincipal);
	}

	/**
	 * @return value of SAMLRequest_SAMLResponse
	 */
	public final saml20.proxies.SAMLResponse getSAMLRequest_SAMLResponse() throws com.mendix.core.CoreException
	{
		return getSAMLRequest_SAMLResponse(getContext());
	}

	/**
	 * @param context
	 * @return value of SAMLRequest_SAMLResponse
	 */
	public final saml20.proxies.SAMLResponse getSAMLRequest_SAMLResponse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.SAMLResponse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SAMLRequest_SAMLResponse.toString());
		if (identifier != null)
			result = saml20.proxies.SAMLResponse.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SAMLRequest_SAMLResponse
	 * @param samlrequest_samlresponse
	 */
	public final void setSAMLRequest_SAMLResponse(saml20.proxies.SAMLResponse samlrequest_samlresponse)
	{
		setSAMLRequest_SAMLResponse(getContext(), samlrequest_samlresponse);
	}

	/**
	 * Set value of SAMLRequest_SAMLResponse
	 * @param context
	 * @param samlrequest_samlresponse
	 */
	public final void setSAMLRequest_SAMLResponse(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.SAMLResponse samlrequest_samlresponse)
	{
		if (samlrequest_samlresponse == null)
			getMendixObject().setValue(context, MemberNames.SAMLRequest_SAMLResponse.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SAMLRequest_SAMLResponse.toString(), samlrequest_samlresponse.getMendixObject().getId());
	}

	/**
	 * @return value of SAMLRequest_SSOConfiguration
	 */
	public final saml20.proxies.SSOConfiguration getSAMLRequest_SSOConfiguration() throws com.mendix.core.CoreException
	{
		return getSAMLRequest_SSOConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of SAMLRequest_SSOConfiguration
	 */
	public final saml20.proxies.SSOConfiguration getSAMLRequest_SSOConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.SSOConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SAMLRequest_SSOConfiguration.toString());
		if (identifier != null)
			result = saml20.proxies.SSOConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SAMLRequest_SSOConfiguration
	 * @param samlrequest_ssoconfiguration
	 */
	public final void setSAMLRequest_SSOConfiguration(saml20.proxies.SSOConfiguration samlrequest_ssoconfiguration)
	{
		setSAMLRequest_SSOConfiguration(getContext(), samlrequest_ssoconfiguration);
	}

	/**
	 * Set value of SAMLRequest_SSOConfiguration
	 * @param context
	 * @param samlrequest_ssoconfiguration
	 */
	public final void setSAMLRequest_SSOConfiguration(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.SSOConfiguration samlrequest_ssoconfiguration)
	{
		if (samlrequest_ssoconfiguration == null)
			getMendixObject().setValue(context, MemberNames.SAMLRequest_SSOConfiguration.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SAMLRequest_SSOConfiguration.toString(), samlrequest_ssoconfiguration.getMendixObject().getId());
	}

	/**
	 * @return value of SAMLRequest_Endpoint
	 */
	public final saml20.proxies.Endpoint getSAMLRequest_Endpoint() throws com.mendix.core.CoreException
	{
		return getSAMLRequest_Endpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of SAMLRequest_Endpoint
	 */
	public final saml20.proxies.Endpoint getSAMLRequest_Endpoint(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.Endpoint result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SAMLRequest_Endpoint.toString());
		if (identifier != null)
			result = saml20.proxies.Endpoint.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SAMLRequest_Endpoint
	 * @param samlrequest_endpoint
	 */
	public final void setSAMLRequest_Endpoint(saml20.proxies.Endpoint samlrequest_endpoint)
	{
		setSAMLRequest_Endpoint(getContext(), samlrequest_endpoint);
	}

	/**
	 * Set value of SAMLRequest_Endpoint
	 * @param context
	 * @param samlrequest_endpoint
	 */
	public final void setSAMLRequest_Endpoint(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.Endpoint samlrequest_endpoint)
	{
		if (samlrequest_endpoint == null)
			getMendixObject().setValue(context, MemberNames.SAMLRequest_Endpoint.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SAMLRequest_Endpoint.toString(), samlrequest_endpoint.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final saml20.proxies.SAMLRequest that = (saml20.proxies.SAMLRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAML20.SAMLRequest";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
