// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public class SPMetadata extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAML20.SPMetadata";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EntityID("EntityID"),
		OrganizationName("OrganizationName"),
		OrganizationDisplayName("OrganizationDisplayName"),
		OrganizationURL("OrganizationURL"),
		ContactGivenName("ContactGivenName"),
		ContactSurName("ContactSurName"),
		ContactEmailAddress("ContactEmailAddress"),
		ApplicationURL("ApplicationURL"),
		DoesEntityIdDifferFromAppURL("DoesEntityIdDifferFromAppURL"),
		LogAvailableDays("LogAvailableDays"),
		UseEncryption("UseEncryption"),
		EncryptionMethod("EncryptionMethod"),
		EncryptionKeyLength("EncryptionKeyLength"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		SPMetadata_KeyStore("SAML20.SPMetadata_KeyStore");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SPMetadata(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAML20.SPMetadata"));
	}

	protected SPMetadata(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sPMetadataMendixObject)
	{
		super(context, sPMetadataMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("SAML20.SPMetadata", sPMetadataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAML20.SPMetadata");
	}

	/**
	 * @deprecated Use 'SPMetadata.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static saml20.proxies.SPMetadata initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return saml20.proxies.SPMetadata.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static saml20.proxies.SPMetadata initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new saml20.proxies.SPMetadata(context, mendixObject);
	}

	public static saml20.proxies.SPMetadata load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return saml20.proxies.SPMetadata.initialize(context, mendixObject);
	}

	public static java.util.List<saml20.proxies.SPMetadata> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<saml20.proxies.SPMetadata> result = new java.util.ArrayList<saml20.proxies.SPMetadata>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SAML20.SPMetadata" + xpathConstraint))
			result.add(saml20.proxies.SPMetadata.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of EntityID
	 */
	public final java.lang.String getEntityID()
	{
		return getEntityID(getContext());
	}

	/**
	 * @param context
	 * @return value of EntityID
	 */
	public final java.lang.String getEntityID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EntityID.toString());
	}

	/**
	 * Set value of EntityID
	 * @param entityid
	 */
	public final void setEntityID(java.lang.String entityid)
	{
		setEntityID(getContext(), entityid);
	}

	/**
	 * Set value of EntityID
	 * @param context
	 * @param entityid
	 */
	public final void setEntityID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String entityid)
	{
		getMendixObject().setValue(context, MemberNames.EntityID.toString(), entityid);
	}

	/**
	 * @return value of OrganizationName
	 */
	public final java.lang.String getOrganizationName()
	{
		return getOrganizationName(getContext());
	}

	/**
	 * @param context
	 * @return value of OrganizationName
	 */
	public final java.lang.String getOrganizationName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrganizationName.toString());
	}

	/**
	 * Set value of OrganizationName
	 * @param organizationname
	 */
	public final void setOrganizationName(java.lang.String organizationname)
	{
		setOrganizationName(getContext(), organizationname);
	}

	/**
	 * Set value of OrganizationName
	 * @param context
	 * @param organizationname
	 */
	public final void setOrganizationName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String organizationname)
	{
		getMendixObject().setValue(context, MemberNames.OrganizationName.toString(), organizationname);
	}

	/**
	 * @return value of OrganizationDisplayName
	 */
	public final java.lang.String getOrganizationDisplayName()
	{
		return getOrganizationDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of OrganizationDisplayName
	 */
	public final java.lang.String getOrganizationDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrganizationDisplayName.toString());
	}

	/**
	 * Set value of OrganizationDisplayName
	 * @param organizationdisplayname
	 */
	public final void setOrganizationDisplayName(java.lang.String organizationdisplayname)
	{
		setOrganizationDisplayName(getContext(), organizationdisplayname);
	}

	/**
	 * Set value of OrganizationDisplayName
	 * @param context
	 * @param organizationdisplayname
	 */
	public final void setOrganizationDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String organizationdisplayname)
	{
		getMendixObject().setValue(context, MemberNames.OrganizationDisplayName.toString(), organizationdisplayname);
	}

	/**
	 * @return value of OrganizationURL
	 */
	public final java.lang.String getOrganizationURL()
	{
		return getOrganizationURL(getContext());
	}

	/**
	 * @param context
	 * @return value of OrganizationURL
	 */
	public final java.lang.String getOrganizationURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrganizationURL.toString());
	}

	/**
	 * Set value of OrganizationURL
	 * @param organizationurl
	 */
	public final void setOrganizationURL(java.lang.String organizationurl)
	{
		setOrganizationURL(getContext(), organizationurl);
	}

	/**
	 * Set value of OrganizationURL
	 * @param context
	 * @param organizationurl
	 */
	public final void setOrganizationURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String organizationurl)
	{
		getMendixObject().setValue(context, MemberNames.OrganizationURL.toString(), organizationurl);
	}

	/**
	 * @return value of ContactGivenName
	 */
	public final java.lang.String getContactGivenName()
	{
		return getContactGivenName(getContext());
	}

	/**
	 * @param context
	 * @return value of ContactGivenName
	 */
	public final java.lang.String getContactGivenName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContactGivenName.toString());
	}

	/**
	 * Set value of ContactGivenName
	 * @param contactgivenname
	 */
	public final void setContactGivenName(java.lang.String contactgivenname)
	{
		setContactGivenName(getContext(), contactgivenname);
	}

	/**
	 * Set value of ContactGivenName
	 * @param context
	 * @param contactgivenname
	 */
	public final void setContactGivenName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contactgivenname)
	{
		getMendixObject().setValue(context, MemberNames.ContactGivenName.toString(), contactgivenname);
	}

	/**
	 * @return value of ContactSurName
	 */
	public final java.lang.String getContactSurName()
	{
		return getContactSurName(getContext());
	}

	/**
	 * @param context
	 * @return value of ContactSurName
	 */
	public final java.lang.String getContactSurName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContactSurName.toString());
	}

	/**
	 * Set value of ContactSurName
	 * @param contactsurname
	 */
	public final void setContactSurName(java.lang.String contactsurname)
	{
		setContactSurName(getContext(), contactsurname);
	}

	/**
	 * Set value of ContactSurName
	 * @param context
	 * @param contactsurname
	 */
	public final void setContactSurName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contactsurname)
	{
		getMendixObject().setValue(context, MemberNames.ContactSurName.toString(), contactsurname);
	}

	/**
	 * @return value of ContactEmailAddress
	 */
	public final java.lang.String getContactEmailAddress()
	{
		return getContactEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of ContactEmailAddress
	 */
	public final java.lang.String getContactEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContactEmailAddress.toString());
	}

	/**
	 * Set value of ContactEmailAddress
	 * @param contactemailaddress
	 */
	public final void setContactEmailAddress(java.lang.String contactemailaddress)
	{
		setContactEmailAddress(getContext(), contactemailaddress);
	}

	/**
	 * Set value of ContactEmailAddress
	 * @param context
	 * @param contactemailaddress
	 */
	public final void setContactEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contactemailaddress)
	{
		getMendixObject().setValue(context, MemberNames.ContactEmailAddress.toString(), contactemailaddress);
	}

	/**
	 * @return value of ApplicationURL
	 */
	public final java.lang.String getApplicationURL()
	{
		return getApplicationURL(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicationURL
	 */
	public final java.lang.String getApplicationURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApplicationURL.toString());
	}

	/**
	 * Set value of ApplicationURL
	 * @param applicationurl
	 */
	public final void setApplicationURL(java.lang.String applicationurl)
	{
		setApplicationURL(getContext(), applicationurl);
	}

	/**
	 * Set value of ApplicationURL
	 * @param context
	 * @param applicationurl
	 */
	public final void setApplicationURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String applicationurl)
	{
		getMendixObject().setValue(context, MemberNames.ApplicationURL.toString(), applicationurl);
	}

	/**
	 * @return value of DoesEntityIdDifferFromAppURL
	 */
	public final java.lang.Boolean getDoesEntityIdDifferFromAppURL()
	{
		return getDoesEntityIdDifferFromAppURL(getContext());
	}

	/**
	 * @param context
	 * @return value of DoesEntityIdDifferFromAppURL
	 */
	public final java.lang.Boolean getDoesEntityIdDifferFromAppURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DoesEntityIdDifferFromAppURL.toString());
	}

	/**
	 * Set value of DoesEntityIdDifferFromAppURL
	 * @param doesentityiddifferfromappurl
	 */
	public final void setDoesEntityIdDifferFromAppURL(java.lang.Boolean doesentityiddifferfromappurl)
	{
		setDoesEntityIdDifferFromAppURL(getContext(), doesentityiddifferfromappurl);
	}

	/**
	 * Set value of DoesEntityIdDifferFromAppURL
	 * @param context
	 * @param doesentityiddifferfromappurl
	 */
	public final void setDoesEntityIdDifferFromAppURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean doesentityiddifferfromappurl)
	{
		getMendixObject().setValue(context, MemberNames.DoesEntityIdDifferFromAppURL.toString(), doesentityiddifferfromappurl);
	}

	/**
	 * @return value of LogAvailableDays
	 */
	public final java.lang.Integer getLogAvailableDays()
	{
		return getLogAvailableDays(getContext());
	}

	/**
	 * @param context
	 * @return value of LogAvailableDays
	 */
	public final java.lang.Integer getLogAvailableDays(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.LogAvailableDays.toString());
	}

	/**
	 * Set value of LogAvailableDays
	 * @param logavailabledays
	 */
	public final void setLogAvailableDays(java.lang.Integer logavailabledays)
	{
		setLogAvailableDays(getContext(), logavailabledays);
	}

	/**
	 * Set value of LogAvailableDays
	 * @param context
	 * @param logavailabledays
	 */
	public final void setLogAvailableDays(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer logavailabledays)
	{
		getMendixObject().setValue(context, MemberNames.LogAvailableDays.toString(), logavailabledays);
	}

	/**
	 * @return value of UseEncryption
	 */
	public final java.lang.Boolean getUseEncryption()
	{
		return getUseEncryption(getContext());
	}

	/**
	 * @param context
	 * @return value of UseEncryption
	 */
	public final java.lang.Boolean getUseEncryption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseEncryption.toString());
	}

	/**
	 * Set value of UseEncryption
	 * @param useencryption
	 */
	public final void setUseEncryption(java.lang.Boolean useencryption)
	{
		setUseEncryption(getContext(), useencryption);
	}

	/**
	 * Set value of UseEncryption
	 * @param context
	 * @param useencryption
	 */
	public final void setUseEncryption(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean useencryption)
	{
		getMendixObject().setValue(context, MemberNames.UseEncryption.toString(), useencryption);
	}

	/**
	 * Set value of EncryptionMethod
	 * @param encryptionmethod
	 */
	public final saml20.proxies.EncryptionMethod getEncryptionMethod()
	{
		return getEncryptionMethod(getContext());
	}

	/**
	 * @param context
	 * @return value of EncryptionMethod
	 */
	public final saml20.proxies.EncryptionMethod getEncryptionMethod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EncryptionMethod.toString());
		if (obj == null)
			return null;

		return saml20.proxies.EncryptionMethod.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EncryptionMethod
	 * @param encryptionmethod
	 */
	public final void setEncryptionMethod(saml20.proxies.EncryptionMethod encryptionmethod)
	{
		setEncryptionMethod(getContext(), encryptionmethod);
	}

	/**
	 * Set value of EncryptionMethod
	 * @param context
	 * @param encryptionmethod
	 */
	public final void setEncryptionMethod(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.EncryptionMethod encryptionmethod)
	{
		if (encryptionmethod != null)
			getMendixObject().setValue(context, MemberNames.EncryptionMethod.toString(), encryptionmethod.toString());
		else
			getMendixObject().setValue(context, MemberNames.EncryptionMethod.toString(), null);
	}

	/**
	 * Set value of EncryptionKeyLength
	 * @param encryptionkeylength
	 */
	public final saml20.proxies.EncryptionKeyLength getEncryptionKeyLength()
	{
		return getEncryptionKeyLength(getContext());
	}

	/**
	 * @param context
	 * @return value of EncryptionKeyLength
	 */
	public final saml20.proxies.EncryptionKeyLength getEncryptionKeyLength(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EncryptionKeyLength.toString());
		if (obj == null)
			return null;

		return saml20.proxies.EncryptionKeyLength.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EncryptionKeyLength
	 * @param encryptionkeylength
	 */
	public final void setEncryptionKeyLength(saml20.proxies.EncryptionKeyLength encryptionkeylength)
	{
		setEncryptionKeyLength(getContext(), encryptionkeylength);
	}

	/**
	 * Set value of EncryptionKeyLength
	 * @param context
	 * @param encryptionkeylength
	 */
	public final void setEncryptionKeyLength(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.EncryptionKeyLength encryptionkeylength)
	{
		if (encryptionkeylength != null)
			getMendixObject().setValue(context, MemberNames.EncryptionKeyLength.toString(), encryptionkeylength.toString());
		else
			getMendixObject().setValue(context, MemberNames.EncryptionKeyLength.toString(), null);
	}

	/**
	 * @return value of SPMetadata_KeyStore
	 */
	public final saml20.proxies.KeyStore getSPMetadata_KeyStore() throws com.mendix.core.CoreException
	{
		return getSPMetadata_KeyStore(getContext());
	}

	/**
	 * @param context
	 * @return value of SPMetadata_KeyStore
	 */
	public final saml20.proxies.KeyStore getSPMetadata_KeyStore(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		saml20.proxies.KeyStore result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SPMetadata_KeyStore.toString());
		if (identifier != null)
			result = saml20.proxies.KeyStore.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SPMetadata_KeyStore
	 * @param spmetadata_keystore
	 */
	public final void setSPMetadata_KeyStore(saml20.proxies.KeyStore spmetadata_keystore)
	{
		setSPMetadata_KeyStore(getContext(), spmetadata_keystore);
	}

	/**
	 * Set value of SPMetadata_KeyStore
	 * @param context
	 * @param spmetadata_keystore
	 */
	public final void setSPMetadata_KeyStore(com.mendix.systemwideinterfaces.core.IContext context, saml20.proxies.KeyStore spmetadata_keystore)
	{
		if (spmetadata_keystore == null)
			getMendixObject().setValue(context, MemberNames.SPMetadata_KeyStore.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SPMetadata_KeyStore.toString(), spmetadata_keystore.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final saml20.proxies.SPMetadata that = (saml20.proxies.SPMetadata) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAML20.SPMetadata";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
