// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public enum TypeOfAuthnContext
{
	MINIMUM(new java.lang.String[][] { new java.lang.String[] { "en_US", "Minimum (Stronger than)" }, new java.lang.String[] { "nl_NL", "Minimum (Sterker dan)" }, new java.lang.String[] { "en_GB", "Minimum (Stronger than)" }, new java.lang.String[] { "en_ZA", "Minimum (Stronger than)" }, new java.lang.String[] { "ja_JP", "Minimum (Stronger than)" } }),
	MAXIMUM(new java.lang.String[][] { new java.lang.String[] { "en_US", "Maximum (No stronger than)" }, new java.lang.String[] { "nl_NL", "Maximum (Niet sterker dan)" }, new java.lang.String[] { "en_GB", "Maximum (No stronger than)" }, new java.lang.String[] { "en_ZA", "Maximum (No stronger than)" }, new java.lang.String[] { "ja_JP", "Maximum (No stronger than)" } }),
	EXACT(new java.lang.String[][] { new java.lang.String[] { "en_US", "Exact (Default)" }, new java.lang.String[] { "nl_NL", "Exact (Standaard)" }, new java.lang.String[] { "en_GB", "Exact (Default)" }, new java.lang.String[] { "en_ZA", "Exact (Default)" }, new java.lang.String[] { "ja_JP", "Exact (Default)" } }),
	BETTER(new java.lang.String[][] { new java.lang.String[] { "en_US", "Better (At least as strong as)" }, new java.lang.String[] { "nl_NL", "Beter (Minstens zo sterk als)" }, new java.lang.String[] { "en_GB", "Better (At least as strong as)" }, new java.lang.String[] { "en_ZA", "Better (At least as strong as)" }, new java.lang.String[] { "ja_JP", "Better (At least as strong as)" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private TypeOfAuthnContext(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
