// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package saml20.proxies;

public enum WizardStepCollection
{
	Step1(new java.lang.String[][] { new java.lang.String[] { "en_US", "Step1" }, new java.lang.String[] { "nl_NL", "Stap 1" }, new java.lang.String[] { "en_GB", "Step1" }, new java.lang.String[] { "en_ZA", "Step1" }, new java.lang.String[] { "ja_JP", "Step1" } }),
	Step2(new java.lang.String[][] { new java.lang.String[] { "en_US", "Step2" }, new java.lang.String[] { "nl_NL", "Stap 2" }, new java.lang.String[] { "en_GB", "Step2" }, new java.lang.String[] { "en_ZA", "Step2" }, new java.lang.String[] { "ja_JP", "Step2" } }),
	Step3(new java.lang.String[][] { new java.lang.String[] { "en_US", "Step3" }, new java.lang.String[] { "nl_NL", "Stap 3" }, new java.lang.String[] { "en_GB", "Step3" }, new java.lang.String[] { "en_ZA", "Step3" }, new java.lang.String[] { "ja_JP", "Step3" } }),
	Step4(new java.lang.String[][] { new java.lang.String[] { "en_US", "Step4" }, new java.lang.String[] { "nl_NL", "Stap 4" }, new java.lang.String[] { "en_GB", "Step4" }, new java.lang.String[] { "en_ZA", "Step4" }, new java.lang.String[] { "ja_JP", "Step4" } }),
	Step5(new java.lang.String[][] { new java.lang.String[] { "en_US", "Step5" }, new java.lang.String[] { "nl_NL", "Stap 5" }, new java.lang.String[] { "en_GB", "Step5" }, new java.lang.String[] { "en_ZA", "Step5" }, new java.lang.String[] { "ja_JP", "Step5" } }),
	Step6(new java.lang.String[][] { new java.lang.String[] { "en_US", "Step6" }, new java.lang.String[] { "nl_NL", "Stap 6" }, new java.lang.String[] { "en_GB", "Step6" }, new java.lang.String[] { "en_ZA", "Step6" }, new java.lang.String[] { "ja_JP", "Step6" } }),
	Step7(new java.lang.String[][] { new java.lang.String[] { "en_US", "Step7" }, new java.lang.String[] { "en_GB", "Step7" }, new java.lang.String[] { "en_ZA", "Step7" }, new java.lang.String[] { "nl_NL", "Stap 7" }, new java.lang.String[] { "ja_JP", "Step7" } }),
	Step8(new java.lang.String[][] { new java.lang.String[] { "en_US", "Step8" }, new java.lang.String[] { "en_GB", "Step8" }, new java.lang.String[] { "en_ZA", "Step8" }, new java.lang.String[] { "nl_NL", "Stap 8" }, new java.lang.String[] { "ja_JP", "Step8" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private WizardStepCollection(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
